version: 0.1.{build}
branches:
  only:
  - master
os: Visual Studio 2013
configuration:
- Debug
- Release
platform:
- x86
- x64
shallow_clone: true
install:
  - cinst swig
  - cinst 7zip.commandline
build:
  project: VS2010/fann.sln
  parallel: true
  verbosity: normal
